name: Build and deploy ASP.NET Core app to Azure Web App - allmcp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SOLUTION_FILE: AllMCPSolution/AllMCPSolution.sln
  PUBLISH_DIR: out/publish

jobs:
  build:
    runs-on: ubuntu-latest   # faster; fine even if App Service is Windows
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # change to 9.x only if your app targets it AND your App Service supports it

      - name: Restore
        run: dotnet restore "$SOLUTION_FILE"

      - name: Build (Release)
        run: dotnet build "$SOLUTION_FILE" -c Release --no-restore

      - name: Publish
        run: dotnet publish "$SOLUTION_FILE" -c Release -o "$PUBLISH_DIR" /p:UseAppHost=false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CF6590494F84DAF8AB63647018CDF76 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0519F7ADB72444BAA1456606AD3FF3BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7CD4A1E210C149CE82E5A43E717D88CC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: allmcp
          slot-name: Production
          package: ./webapp
